front da tela de cadastro finalizada
Pycem-sptech/site-institucional pull request #1
Opened 2023-02-17 15:39 UTC by the-cris-code

tela de cadastro finalizada conforme prototipo. realizar testes e validação.

2023-02-17 18:35 UTC, M4theusRibeiro approved these changes
Ficou muito bom! Parabéns!

2023-02-17 18:58 UTC, pedro-l0pes approved these changes

2023-02-17 20:11 UTC, EduardoDamSilva approved these changes
Aprovado

2023-02-17 21:46 UTC, Yah-olih approved these changes
esta muito bom

2023-02-17 23:33 UTC, Yah-olih requested changes
Requisito  que falta: CNPJ 
No cadastro e cadastro de usuário

2023-02-17 23:36 UTC, Yah-olih requested changes
Nome do cadastro e "Cadastro de empresa"

2023-02-20 22:55 UTC, Yah-olih requested changes
colocar - confirmação de senha

2023-03-02 21:06 UTC, closed without merging