Página home finalizada e BackEnd nodejs
Pycem-sptech/site-institucional pull request #3
Opened 2023-02-22 01:11 UTC by M4theusRibeiro

2023-02-22 13:16 UTC, the-cris-code requested changes
border bottom do header está ocupando somente 80% da largura da tela e deve ocupar 100%. navbar não tem o botão pagina inicial no protótipo pois já contém os botões "produto", "sobre nós" e "solução" que já direcionam para a página inicial.

2023-02-22 23:17 UTC, EduardoDamSilva approved these changes

2023-02-23 00:07 UTC, Yah-olih requested changes
Na parte de Área de Benefícios a margem dos 4 quadrados não está centralizado do site, seu fundo está muito escuro e ele e mais cumprido e menos achatado.
A fonte dos parágrafos está inclinado sendo que e reta, sua cor está preto porém e cinza.
o campo com o titulo área de benéficos e seu paragrafo não está centralizado.

2023-02-23 00:09 UTC, Yah-olih approved these changes

2023-02-23 19:20 UTC, pedro-l0pes approved these changes

2023-02-23 19:22 UTC, merged